fix warnings when compiling with gcc8
E.g. when compiling with gcc8 with warnings as errors you'll get the following:

    mode_s.c: In function 'nav_modes_to_string':
    mode_s.c:1626:9: error: 'strncat' specified bound 10 equals source length [-Werror=stringop-overflow=]
    strncat(buf, "autopilot ", 10);
    ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

This error is indicating that you should be using strcat instead of strncat
since the length of source is same as the bound.